call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-vinegar'
Plug 'Valloric/YouCompleteMe'
Plug 'SirVer/ultisnips'
Plug 'w0rp/ale'
Plug 'mileszs/ack.vim'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'othree/yajs.vim'
Plug 'mxw/vim-jsx'
Plug 'prettier/vim-prettier'
Plug 'dracula/vim'
Plug 'arcticicestudio/nord-vim'

call plug#end()

set number
set background=dark
colorscheme nord
set ts=2 sts=2 sw=2 expandtab

let b:ale_linters = {'javascript': ['eslint'], 'python': ['flake8']}
let g:prettier#config#single_quote = 'false'


"" bindings
let mapleader=" "
nmap ; :Buffers<CR>
nmap <Leader>s :Files<CR>
nmap <Leader>r :Tags<CR>
nmap <Leader>k :Ack! "\b<cword>\b" <CR>
nmap <Leader>t :bp\|bd #<CR>

nmap <silent> gd :YcmCompleter GoTo<CR>
"nmap <silent> gy <Plug>(coc-type-definition)
"nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr :YcmCompleter GoToReferences<CR>


